/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kunDict;

import org.junit.Test;
import static org.junit.Assert.*;
import java.net.http.HttpResponse;
import java.nio.file.Paths;


public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testRequest() {
        String url = "https://www.collinsdictionary.com/us/dictionary/english/water";
        String fileName = "water.html";
        Request req = new Request(url);
        req.bodyHandler = HttpResponse.BodyHandlers.ofFile(
                Paths.get(fileName));
        HttpResponse<String> response = req.get();

        // System.out.println(response.body().substring(0, 500));
        assertEquals(200, response.statusCode());
        assertNotNull("request should get response", response);
    }
}
