/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kunDict;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testRequest() {
        String url = "https://www.collinsdictionary.com/us/dictionary/english/water";
        Request req = new Request(url);
        String html = req.get();
        System.out.println(html.substring(0, 500));
        assertNotNull("request should get html String", html);
    }
}
